import type { Metadata } from "next"
import "./globals.css"
import { lexend } from "./ui/fonts/fonts" // fonte

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>
        {/* Conteúdo da página */}
        {children}
      </body>
    </html>
  )
}
